version: '3.0'
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - ./config/jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped
    labels:
      - 'com.centurylinklabs.watchtower.monitor-only=true'
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - ./config/sonarr:/config
      - /mnt/data:/mnt/data
    ports:
      - 8989:8989
    depends_on:
      - jackett
      - transmission
      - sabnzbd
    restart: unless-stopped
    labels:
      - 'com.centurylinklabs.watchtower.monitor-only=true'
  radarr:
    image: linuxserver/radarr:preview
    container_name: radarr
    hostname: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - ./config/radarr:/config
      - /mnt/data:/mnt/data
    ports:
      - 7878:7878
    depends_on:
      - jackett
      - transmission
      - sabnzbd
    restart: unless-stopped
    labels:
      - 'com.centurylinklabs.watchtower.monitor-only=true'
  transmission:
    # https://haugene.github.io/docker-transmission-openvpn/
    image: haugene/transmission-openvpn
    container_name: transmission
    volumes:
      - /mnt/data:/mnt/data
    environment:
      - PUID=1000
      - PGID=1000
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=NORDVPN
      - NORDVPN_COUNTRY=DE
      - OPENVPN_USERNAME=username
      - OPENVPN_PASSWORD=pass
      - WEBPROXY_ENABLED=false
      - TRANSMISSION_DOWNLOAD_DIR=/mnt/data/downloads
      - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
      - TRANSMISSION_SEED_QUEUE_ENABLED=true
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=false
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT=2
      - LOCAL_NETWORK=192.168.0.0/16
    cap_add:
      - NET_ADMIN
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - '9091:9091'
    restart: unless-stopped
    labels:
      - 'com.centurylinklabs.watchtower.monitor-only=true'
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - ./config/sabnzbd:/config
      - /mnt/data/downloads:/downloads
    ports:
      - 7070:8080
      - 9090:9090
    restart: unless-stopped
    labels:
      - 'com.centurylinklabs.watchtower.monitor-only=true'
  plex:
    image: linuxserver/plex
    container_name: plex
    volumes:
      - /mnt/data/media:/media
      - ./config/plex:/config
    # Uncomment the below if you've got hardware acceleration available
    # devices:
    #   - '/dev/dri:/dev/dri'
    environment:
      - PUID=1000
      - PGID=1000
      - version=docker
    ports:
      - 32400:32400
    restart: unless-stopped
    labels:
      - 'com.centurylinklabs.watchtower.monitor-only=true'
  tautulli:
    image: tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - ./config/tautulli:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    ports:
      - 8181:8181
    labels:
      - 'com.centurylinklabs.watchtower.monitor-only=true'
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Lisbon
    ports:
      - 5055:5055
    volumes:
      - ./config/overseerr:/app/config
    restart: unless-stopped
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
